import {validateContent,imagePaths} from './content-schema.js';
import {renderHomepage} from './content-renderer.js';
const $=s=>document.querySelector(s);
let content,revision,published,section='hero',connected=false,busy=false,dirty=false,draftSaved=true,uploads=new Map(),saveTimer,generation=0,requestId=crypto.randomUUID(),deploymentTimer;
const names={hero:'Prima secțiune',services:'Servicii',gallery:'Galerie foto & video',about:'Despre noi',process:'Cum lucrăm',faq:'Întrebări frecvente',contact:'Contact & Google Maps'};
const status=(message,tone='error',target='#editor-status')=>{$(target).textContent=message;$(target).dataset.tone=tone;};
function node(tag,text,classes){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(classes)n.className=classes;return n;}
async function api(route,options={}){const response=await fetch('/api/editor'+route,{credentials:'same-origin',cache:'no-store',...options});const data=await response.json().catch(()=>({error:'Administrarea online nu este încă activată.'}));if(!response.ok||data.error){if(response.status===401&&route!=='/login'){connected=false;updateButtons();}throw new Error(data.error||'Cererea nu a putut fi finalizată.');}return data;}
const json=body=>({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
const database=new Promise((resolve,reject)=>{const r=indexedDB.open('abt-cleaning-services-editor',1);r.onupgradeneeded=()=>r.result.createObjectStore('drafts');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
async function draftStorage(action,value){const db=await database;return new Promise((resolve,reject)=>{const tx=db.transaction('drafts',action==='get'?'readonly':'readwrite'),store=tx.objectStore('drafts');const r=action==='get'?store.get('current'):action==='put'?store.put(value,'current'):store.delete('current');tx.oncomplete=()=>resolve(r.result);tx.onerror=()=>reject(tx.error);});}
function updateButtons(){$('#publish-content').disabled=busy||!dirty||!connected;$('#reload-content').disabled=busy;$('#export-draft').disabled=busy;$('#open-preview').disabled=busy;$('#editor-fields').querySelectorAll('input,textarea,select,button').forEach(n=>n.disabled=busy||n.dataset.limitDisabled==='true');$('.section-nav').querySelectorAll('button').forEach(n=>n.disabled=busy);$('#editor-logout').disabled=busy;}
function setBusy(value){busy=value;updateButtons();}
function markDirty(){clearInterval(deploymentTimer);dirty=true;draftSaved=false;requestId=crypto.randomUUID();const current=++generation;updateButtons();$('#draft-status').textContent='Se salvează ciorna...';clearTimeout(saveTimer);saveTimer=setTimeout(async()=>{if(current!==generation||!dirty)return;try{await draftStorage('put',{content,revision,uploads:[...uploads],requestId});if(current!==generation||!dirty)return;draftSaved=true;$('#draft-status').textContent='Ciornă salvată în acest browser. Modificările nu sunt publicate.';}catch{if(current===generation)$('#draft-status').textContent='Ciorna nu a putut fi salvată. Descarcă o copie înainte de a închide pagina.';}},400);}
function field(parent,label,object,key,{multiline=false,help='',type='text',limit=2000}={}){const wrap=node('div',undefined,'field-wrap');const id='field-'+crypto.randomUUID();const lbl=node('label',label);lbl.htmlFor=id;const input=node(multiline?'textarea':'input');input.id=id;input.value=object[key];input.maxLength=limit;if(multiline)input.rows=3;else input.type=type;input.addEventListener('input',()=>{object[key]=input.value;markDirty();});wrap.append(lbl,input);if(help){const p=node('p',help,'field-help');p.id=id+'-help';input.setAttribute('aria-describedby',p.id);wrap.append(p);}parent.append(wrap);return input;}
function button(parent,label,action,classes){const b=node('button',label,classes);b.type='button';b.addEventListener('click',action);parent.append(b);return b;}
function headingFields(parent,value){const grid=node('div',undefined,'field-grid');field(grid,'Reperele de deasupra titlului',value,'eyebrow',{limit:120});field(grid,'Titlul principal',value,'title',{limit:160});field(grid,'Partea scrisă cursiv',value,'accent',{limit:160});parent.append(grid);}
function reorder(list,index,delta){const next=index+delta;if(next<0||next>=list.length)return;[list[index],list[next]]=[list[next],list[index]];markDirty();renderFields();}
function remove(list,index,min=0){if(list.length<=min){status('Păstrează cel puțin un element în această secțiune.');return;}if(!confirm('Elimini acest element din ciornă? Site-ul se schimbă doar după publicare.'))return;list.splice(index,1);markDirty();renderFields();}
function ordering(parent,list,index,min=0){for(const [label,delta] of [['Mai sus',-1],['Mai jos',1]]){const b=button(parent,label,()=>reorder(list,index,delta));b.disabled=index+delta<0||index+delta>=list.length;b.dataset.limitDisabled=String(b.disabled);}button(parent,'Elimină',()=>remove(list,index,min),'danger');}
function imageURL(src){const u=uploads.get(src);return u?'data:'+u.type+';base64,'+u.base64:src;}
async function prepareImage(file){
 if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>20*1024*1024)throw new Error('Alege o fotografie JPG, PNG sau WebP de maxim 20 MB.');
 const url=URL.createObjectURL(file),image=new Image();
 try{image.src=url;await image.decode();const scale=Math.min(1,1800/Math.max(image.naturalWidth,image.naturalHeight)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/webp',.85));if(!blob||blob.size>2*1024*1024)throw new Error('Fotografia este prea mare. Alege o imagine mai mică.');const bytes=new Uint8Array(await blob.arrayBuffer()),hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(v=>v.toString(16).padStart(2,'0')).join('');let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.slice(i,i+8192));const path='assets/uploads/'+hash+'.webp';uploads.set(path,{path,base64:btoa(binary),type:'image/webp'});return{src:path,alt:'',width:canvas.width,height:canvas.height};}finally{URL.revokeObjectURL(url);}
}
function imageEditor(parent,object,key){const photo=object[key],card=node('div',undefined,'image-card'),img=node('img');img.src=imageURL(photo.src);img.alt=photo.alt;card.append(img);const actions=node('div',undefined,'card-actions');button(actions,'Schimbă fotografia',()=>{const input=node('input');input.type='file';input.accept='image/jpeg,image/png,image/webp';input.className='image-input';document.body.append(input);input.addEventListener('change',async()=>{const file=input.files[0];if(!file){input.remove();return;}setBusy(true);status('Se optimizează fotografia...','info');try{const next=await prepareImage(file);object[key]={...next,alt:photo.alt};markDirty();renderFields();status('Fotografie adăugată în ciornă. Nu este încă publicată.','info');}catch(e){status(e.message);}finally{setBusy(false);input.remove();}});input.click();});card.append(actions);field(card,'Descrierea fotografiei',photo,'alt',{limit:300,help:'Descrie imaginea pentru persoanele care folosesc un cititor de ecran.'});parent.append(card);}
function stringList(parent,label,list){parent.append(node('label',label,'string-list-label'));list.forEach((value,i)=>{const row=node('div',undefined,'string-item'),input=node('input');input.value=value;input.maxLength=300;input.setAttribute('aria-label',label+' '+(i+1));input.addEventListener('input',()=>{list[i]=input.value;markDirty();});row.append(input);button(row,'Elimină',()=>remove(list,i),'danger');parent.append(row);});button(parent,'Adaugă un detaliu',()=>{if(list.length>=12){status('Poți adăuga maxim 12 detalii.');return;}list.push('');markDirty();renderFields();},'add-button');}
function renderList(parent,list,type){
 list.forEach((item,i)=>{const card=node('div',undefined,'item-edit'),head=node('div',undefined,'item-head');head.append(node('h3',(type==='faq'?'Întrebarea ':type==='service'?'Serviciul ':'Elementul ')+(i+1)));const actions=node('div',undefined,'card-actions');ordering(actions,list,i,type==='service'?1:0);head.append(actions);card.append(head);
 if(type==='faq'){field(card,'Întrebare',item,'question',{limit:200});field(card,'Răspuns',item,'answer',{multiline:true,limit:3000});}
 else{field(card,'Titlu',item,'title',{limit:160});if(type==='service'){field(card,'Subtitlu',item,'subtitle',{limit:160});selectField(card,'Categoria serviciului',item,'category',[['acasa','Acasă'],['business','Spații profesionale'],['special','Specializate']]);}field(card,'Descriere',item,'body',{multiline:true});if(type==='service'){imageEditor(card,item,'image');stringList(card,'Ce include serviciul',item.details);}}
 parent.append(card);});
 button(parent,type==='faq'?'Adaugă o întrebare':type==='service'?'Adaugă un serviciu':'Adaugă un element',()=>{const limit=type==='faq'?20:type==='service'?12:8;if(list.length>=limit){status('Ai ajuns la limita de elemente pentru această secțiune.');return;}list.push(type==='faq'?{question:'Întrebare nouă',answer:''}:type==='service'?{id:crypto.randomUUID(),category:'acasa',title:'Serviciu nou',subtitle:'',body:'',image:structuredClone(content.hero.image),details:[]}:{title:'Element nou',body:''});markDirty();renderFields();},'add-button');
}
function renderFields(){const root=$('#editor-fields');root.replaceChildren();if(!content)return;const v=content[section],panel=node('section',undefined,'editor-panel');panel.append(node('h2',names[section]),node('p','Scrie direct în câmpuri. Verifică rezultatul în previzualizare înainte de publicare.','panel-intro'));root.append(panel);
 if(section==='hero'){const grid=node('div',undefined,'field-grid');field(grid,'Textul de deasupra titlului',v,'eyebrow',{limit:120});field(grid,'Titlul principal',v,'heading',{limit:160});field(grid,'Partea scrisă cursiv',v,'accent',{limit:160});field(grid,'Textul butonului',v,'cta',{limit:80});panel.append(grid);field(panel,'Introducere',v,'intro',{multiline:true});imageEditor(panel,v,'image');field(panel,'Eticheta de pe fotografie',v,'imageLabel',{limit:100});field(panel,'Textul de sub fotografie',v,'imageCaption',{limit:160});}
 else{headingFields(panel,v);
 if(['services','gallery','about','process','contact'].includes(section))field(panel,'Introducere',v,'intro',{multiline:true});
 if(section==='services')renderList(panel,v.items,'service');
 if(section==='gallery')renderGalleryEditor(panel,v);
 if(section==='about'){field(panel,'Textul despre firmă',v,'body',{multiline:true,limit:5000});renderList(panel,v.points,'point');}
 if(section==='process')renderList(panel,v.steps,'step');
 if(section==='faq')renderList(panel,v.items,'faq');
 if(section==='contact'){
 const grid=node('div',undefined,'field-grid');field(grid,'Telefon',v,'phone',{type:'tel',limit:80,help:'Actualizează numărul afișat și toate linkurile pentru apel.'});field(grid,'Email (opțional)',v,'email',{type:'email',limit:254});field(grid,'Adresa afișată',v,'address',{limit:1000});field(grid,'Program / informații despre programare',v,'hours',{multiline:true,limit:1000});panel.append(grid);
 field(panel,'Link WhatsApp',v,'whatsappUrl',{type:'url',limit:1000,help:'Include prefixul de țară în link: https://wa.me/407XXXXXXXX. Lasă gol pentru a ascunde butonul.'});field(panel,'Link Facebook',v,'facebookUrl',{type:'url',limit:1000});
 const maps=node('section',undefined,'editor-panel');maps.append(node('h2','Google Maps'));field(maps,'Linkul pinului firmei',v,'mapsUrl',{type:'url',limit:4000});field(maps,'Link pentru indicații',v,'directionsUrl',{type:'url',limit:4000});field(maps,'Linkul hărții încorporate',v,'mapEmbedUrl',{multiline:true,limit:4000,help:'În Google Maps alege Trimite, Încorporează o hartă. Introdu doar adresa din atributul src, nu întregul cod iframe.'});const rating=node('div',undefined,'field-grid');field(rating,'Evaluarea Google',v,'rating',{limit:10,help:'De exemplu 5,0. Lasă gol pentru a ascunde evaluarea.'});field(rating,'Numărul recenziilor Google',v,'reviewCount',{limit:10,help:'Se actualizează manual după verificare pe Google Maps.'});maps.append(rating);root.append(maps);
 }}updateButtons();
}
async function publicContent(){const r=await fetch('assets/site-content.json?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('Conținutul public nu a putut fi încărcat.');return validateContent(await r.json());}
async function showWorkspace(local=false){
 setBusy(true);try{
 const data=local?{content:await publicContent(),revision:null}:await api('/content');content=validateContent(data.content);revision=data.revision;published=structuredClone(content);uploads=new Map();dirty=false;draftSaved=true;connected=!local;
 const stored=await draftStorage('get').catch(()=>null);if(stored){try{const restored=validateContent(stored.content);content=restored;revision=stored.revision;uploads=new Map(stored.uploads||[]);requestId=stored.requestId||crypto.randomUUID();dirty=true;}catch{status('O ciornă veche nu a putut fi restaurată. Versiunea publicată este disponibilă.');}}
 $('#editor-auth').hidden=true;$('#editor-workspace').hidden=false;$('#editor-logout').hidden=local;$('#connection-status').textContent=local?'MOD LOCAL / PUBLICAREA NU ESTE ACTIVATĂ':'CONECTAT / EDITORUL SITE-ULUI';
 $('#draft-status').textContent=dirty?'Ciorna salvată în acest browser a fost restaurată. Modificările nu sunt publicate.':'Nu există modificări nepublicate.';
 if(local)status('Poți edita și previzualiza. Publicarea va fi disponibilă după conectarea conturilor clientului.','info');else status('Editorul este conectat.','success');
 renderFields();
 }finally{setBusy(false);}
}
$('.section-nav').querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{section=b.dataset.section;$('.section-nav').querySelectorAll('button').forEach(n=>n.setAttribute('aria-pressed',String(n===b)));renderFields();}));
$('#open-demo').addEventListener('click',()=>showWorkspace(true).catch(e=>status(e.message,'error','#auth-status')));
$('#editor-login').addEventListener('submit',async event=>{event.preventDefault();const submit=event.currentTarget.querySelector('button');submit.disabled=true;try{await api('/login',json({username:$('#editor-user').value,password:$('#editor-password').value}));$('#editor-password').value='';await showWorkspace();}catch(e){status(e.message,'error','#auth-status');$('#setup-note').hidden=false;}finally{submit.disabled=false;}});
$('#editor-logout').addEventListener('click',async()=>{try{await api('/logout',json({}));connected=false;$('#editor-auth').hidden=false;$('#editor-workspace').hidden=true;$('#editor-logout').hidden=true;status('Ai ieșit din cont. Ciorna este păstrată în acest browser.','info','#auth-status');}catch(e){status(e.message);}});
$('#reload-content').addEventListener('click',async()=>{if(dirty&&!confirm('Elimini modificările nepublicate și reîncarci ultima versiune?'))return;setBusy(true);clearTimeout(saveTimer);++generation;try{const data=connected?await api('/content'):{content:await publicContent(),revision:null};const fresh=validateContent(data.content);await draftStorage('delete');content=fresh;revision=data.revision;published=structuredClone(fresh);uploads.clear();dirty=false;draftSaved=true;requestId=crypto.randomUUID();renderFields();$('#draft-status').textContent='Ultima versiune a fost reîncărcată. Nu există modificări nepublicate.';status('Câmpurile sunt actualizate.','info');}catch(e){status(e.message);if(dirty)markDirty();}finally{setBusy(false);}});
$('#export-draft').addEventListener('click',()=>{try{const clean=validateContent(content);const used=new Set(imagePaths(clean));const blob=new Blob([JSON.stringify({content:clean,revision,uploads:[...uploads].filter(([key])=>used.has(key))},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=node('a');a.href=url;a.download='abt-cleaning-services-ciorna.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('Copia ciornei a fost descărcată. Modificările nu sunt publicate.','info');}catch(e){status(e.message);}});
$('#open-preview').addEventListener('click',()=>{try{const clean=validateContent(content);$('#site-preview').srcdoc=renderHomepage(clean,{base:new URL('./',location.href).href,imageUrl:imageURL,preview:true});$('#preview-dialog').showModal();document.body.classList.add('modal-open');}catch(e){status(e.message);}});
$('#close-preview').addEventListener('click',()=>$('#preview-dialog').close());$('#preview-dialog').addEventListener('close',()=>{document.body.classList.remove('modal-open');$('#open-preview').focus();});
for(const mode of ['desktop','mobile'])$('#preview-'+mode).addEventListener('click',()=>{$('#site-preview').classList.toggle('mobile',mode==='mobile');$('#preview-desktop').setAttribute('aria-pressed',String(mode==='desktop'));$('#preview-mobile').setAttribute('aria-pressed',String(mode==='mobile'));});
$('#publish-content').addEventListener('click',async()=>{if(!connected||busy||!dirty)return;let clean;try{clean=validateContent(content);}catch(e){status(e.message);return;}setBusy(true);clearTimeout(saveTimer);++generation;status('Se salvează modificările...','info');try{const used=new Set(imagePaths(clean)),data=await api('/publish',json({content:clean,revision,requestId,images:[...uploads.values()].filter(v=>used.has(v.path))}));revision=data.revision;content={...clean,publicationId:data.publicationId};published=structuredClone(content);uploads.clear();dirty=false;draftSaved=true;await draftStorage('delete').catch(()=>{});$('#draft-status').textContent='Modificările sunt salvate. Se verifică actualizarea site-ului.';status('Salvat în GitHub. Actualizarea site-ului este în curs.','success');let attempts=0;clearInterval(deploymentTimer);deploymentTimer=setInterval(async()=>{attempts++;try{const latest=await publicContent();if(latest.publicationId===data.publicationId){status('Modificările sunt publicate și vizibile pe site.','success');$('#draft-status').textContent='Site-ul este actualizat.';clearInterval(deploymentTimer);}}catch{}if(attempts>=24){clearInterval(deploymentTimer);status('Modificările sunt salvate. Apariția lor pe site nu a fost încă confirmată. Verifică site-ul peste câteva minute.','info');}},5000);}catch(e){status(e.message);markDirty();}finally{setBusy(false);}});
addEventListener('beforeunload',event=>{if(dirty&&(busy||!draftSaved)){event.preventDefault();event.returnValue='';}});
(async()=>{try{const data=await api('/session');if(data.admin)await showWorkspace();else status('Autentifică-te pentru a modifica site-ul.','info','#auth-status');}catch{status('Administrarea online nu este încă activată.','info','#auth-status');$('#setup-note').hidden=false;}})();

function selectField(parent,label,object,key,options){const wrap=node('div',undefined,'field-wrap'),lbl=node('label',label),input=node('select'),id='select-'+crypto.randomUUID();lbl.htmlFor=id;input.id=id;for(const [value,text] of options){const option=node('option',text);option.value=value;input.append(option);}input.value=object[key];input.addEventListener('change',()=>{object[key]=input.value;markDirty();});wrap.append(lbl,input);parent.append(wrap);}
async function storeBlob(blob,extension){const bytes=new Uint8Array(await blob.arrayBuffer()),hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(v=>v.toString(16).padStart(2,'0')).join('');let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.slice(i,i+8192));const path='assets/uploads/'+hash+'.'+extension;uploads.set(path,{path,type:blob.type,base64:btoa(binary)});return path;}
async function prepareVideo(file){
 if(!['video/mp4','video/webm'].includes(file.type)||file.size>8*1024*1024)throw new Error('Alege un clip MP4 sau WebM de maxim 8 MB.');
 const url=URL.createObjectURL(file),video=document.createElement('video');video.muted=true;video.preload='auto';
 const waitFor=(event,action)=>new Promise((resolve,reject)=>{const timer=setTimeout(()=>finish(new Error('Clipul nu poate fi pregătit. Încearcă un fișier MP4 sau WebM mai mic.')),12000);function finish(error){clearTimeout(timer);video.removeEventListener(event,ready);video.removeEventListener('error',failed);error?reject(error):resolve();}const ready=()=>finish(),failed=()=>finish(new Error('Clipul nu poate fi citit. Alege un MP4 sau WebM valid.'));video.addEventListener(event,ready,{once:true});video.addEventListener('error',failed,{once:true});action();});
 try{await waitFor('loadedmetadata',()=>video.src=url);if(!video.videoWidth||!video.videoHeight||!Number.isFinite(video.duration)||video.duration<=0)throw new Error('Clipul nu are dimensiuni sau durată valide.');await waitFor('seeked',()=>video.currentTime=Math.min(.5,video.duration/2));const scale=Math.min(1,800/Math.max(video.videoWidth,video.videoHeight)),canvas=document.createElement('canvas');canvas.width=Math.round(video.videoWidth*scale);canvas.height=Math.round(video.videoHeight*scale);canvas.getContext('2d').drawImage(video,0,0,canvas.width,canvas.height);const poster=await new Promise(resolve=>canvas.toBlob(resolve,'image/webp',.82));const src=await storeBlob(file,file.type==='video/mp4'?'mp4':'webm');return{src,poster:poster?await storeBlob(poster,'webp'):'',width:video.videoWidth,height:video.videoHeight,alt:''};}finally{video.removeAttribute('src');video.load();URL.revokeObjectURL(url);}
}
function chooseGalleryMedia(type,onDone){const input=node('input');input.type='file';input.accept=type==='video'?'video/mp4,video/webm':'image/jpeg,image/png,image/webp';input.className='image-input';document.body.append(input);input.addEventListener('change',async()=>{const file=input.files[0];if(!file){input.remove();return;}setBusy(true);try{status('Se pregătește fișierul...','info');const media=type==='video'?await prepareVideo(file):await prepareImage(file);onDone(media);markDirty();renderFields();status('Fișierul este adăugat în ciornă. Nu este încă publicat.','info');}catch(error){status(error.message);}finally{input.remove();setBusy(false);}});input.click();}
function renderGalleryEditor(panel,value){panel.append(node('p','Fotografii JPG, PNG sau WebP. Clipuri MP4 sau WebM de maxim 8 MB. Clipurile nu sunt comprimate automat.','field-help'));value.items.forEach((item,i)=>{const card=node('div',undefined,'item-edit'),head=node('div',undefined,'item-head');head.append(node('h3',(item.type==='video'?'Video ':'Fotografie ')+(i+1)));const actions=node('div',undefined,'card-actions');ordering(actions,value.items,i);head.append(actions);card.append(head);if(item.type==='image'){const bridge={get image(){return item;},set image(photo){Object.assign(item,photo);}};imageEditor(card,bridge,'image');}else{const box=node('div',undefined,'image-card'),video=node('video');video.src=imageURL(item.src);video.poster=item.poster?imageURL(item.poster):'';video.controls=true;video.preload='metadata';box.append(video);const actions=node('div',undefined,'card-actions');button(actions,'Schimbă clipul',()=>chooseGalleryMedia('video',media=>Object.assign(item,media)));box.append(actions);card.append(box);}field(card,'Titlu',item,'title',{limit:160});field(card,'Descriere / detalii',item,'caption',{multiline:true,limit:1000});if(item.type==='video')field(card,'Descrierea clipului',item,'alt',{limit:300});field(card,'Link către postarea originală (opțional)',item,'source',{type:'url',limit:4000});panel.append(card);});for(const [label,type] of [['Adaugă o fotografie','image'],['Adaugă un video','video']])button(panel,label,()=>{if(value.items.length>=60){status('Galeria poate avea maxim 60 de elemente.');return;}chooseGalleryMedia(type,media=>value.items.push({id:crypto.randomUUID(),type,title:type==='video'?'Clip nou':'Fotografie nouă',caption:'',source:'',poster:'',...media}));},'add-button');}
