import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {validateContent} from '../content-schema.js';
import {renderHomepage} from '../content-renderer.js';
import worker,{verifyPassword,ApiError,json,readLimited} from '../cloudflare/worker.js';
import {editorApi} from '../cloudflare/editor-api.js';
import {pbkdf2Sync,createHash} from 'node:crypto';
const initial=JSON.parse((await fs.readFile(new URL('../assets/site-content.json',import.meta.url),'utf8')).replace(/^\uFEFF/,''));
test('conținutul inițial este valid, cu căi relative și fără cratime lungi',()=>{const html=renderHomepage(initial);assert.ok(html.includes('assets/gallery/abt-06.webp'));assert.ok(!/[\u2013\u2014]/.test(html));assert.ok(html.includes('ChIJ9QyWZU_7ykARNKqUqN97cq8'));});
test('textul editat este escapate în HTML și nu produce markup executabil',()=>{const c=structuredClone(initial);c.hero.heading='<img src=x onerror=alert(1)>';const html=renderHomepage(c);assert.ok(html.includes('&lt;img src=x onerror=alert(1)&gt;'));assert.ok(!html.includes('<img src=x'));});
test('editorul respinge traversarea directoarelor, URL-uri active și hărți străine',()=>{for(const change of [c=>c.hero.image.src='assets/../secret.png',c=>c.contact.facebookUrl='javascript:alert(1)',c=>c.contact.mapEmbedUrl='https://example.com/maps?output=embed',c=>c.hero.heading='Text'+String.fromCharCode(8212)+'text']){const c=structuredClone(initial);change(c);assert.throws(()=>validateContent(c));}});
test('parolele folosesc PBKDF2 și o parolă greșită nu validează',async()=>{const salt='0'.repeat(32),expected=pbkdf2Sync('parola-locală-de-test',salt,100000,32,'sha256').toString('hex');assert.equal(await verifyPassword('parola-locală-de-test',salt+':'+expected),true);assert.equal(await verifyPassword('gresit',salt+':'+expected),false);});
test('administrarea fără configurare și cererile de login cross origin sunt respinse',async()=>{assert.equal((await worker.fetch(new Request('https://site.test/api/editor/session'),{})).status,503);const env={EDITOR_DB:{},ADMIN_PASSWORD_HASH:'x'};assert.equal((await worker.fetch(new Request('https://site.test/api/editor/login',{method:'POST',headers:{Origin:'https://alt-site.test'},body:'{}'}),env)).status,403);});
test('publicarea salvează video, copertă, conținut și index într-un commit fără force',async()=>{
 const content=structuredClone(initial),uploads=[];const video=content.gallery.items.find(v=>v.type==='video');for(const [field,extension] of [['src','mp4'],['poster','webp']]){const bytes=await fs.readFile(new URL('../'+video[field],import.meta.url));video[field]='assets/uploads/'+createHash('sha256').update(bytes).digest('hex')+'.'+extension;uploads.push({path:video[field],base64:bytes.toString('base64')});}
 const oldFetch=globalThis.fetch,revision='a'.repeat(40),nextRevision='b'.repeat(40),requestId='00000000-0000-4000-8000-000000000000';let tree,update;const blobs=[];
 globalThis.fetch=async(url,options)=>{const pathname=new URL(url).pathname;const body=options?.body?JSON.parse(options.body):null;
 if(pathname.endsWith('/git/ref/heads/main'))return Response.json({object:{sha:revision}});
 if(pathname.endsWith('/contents/assets/site-content.json'))return Response.json({content:Buffer.from(JSON.stringify(initial)).toString('base64')});
 if(pathname.endsWith('/git/commits/'+revision))return Response.json({tree:{sha:'c'.repeat(40)}});
 if(pathname.endsWith('/git/blobs')){blobs.push(Buffer.from(body.content,'base64').toString());return Response.json({sha:blobs.length.toString().repeat(40)});}
 if(pathname.endsWith('/git/trees')){tree=body;return Response.json({sha:'d'.repeat(40)});}
 if(pathname.endsWith('/git/commits'))return Response.json({sha:nextRevision});
 if(pathname.endsWith('/git/refs/heads/main')){update=body;return Response.json({});}
 throw new Error('Cerere neașteptată '+url);
 };
 const env={GITHUB_REPOSITORY:'client/clean',GITHUB_BRANCH:'main',GITHUB_TOKEN:'test-only',EDITOR_DB:{prepare:()=>({bind(){return this},async first(){return null},async run(){return{success:true}}})}};
 try{const response=await editorApi(new Request('https://site.test/api/editor/publish',{method:'POST',headers:{Origin:'https://site.test','Content-Type':'application/json'},body:JSON.stringify({content,revision,requestId,images:uploads})}),env,{requireAdmin:async()=>{},ApiError,json,readLimited});assert.equal(response.status,200);assert.equal(update.force,false);assert.deepEqual(tree.tree.map(v=>v.path),[...uploads.map(v=>v.path),'assets/site-content.json','index.html']);assert.ok(blobs.some(v=>v.includes(video.src)&&v.startsWith('<!doctype html>')));assert.ok(blobs.some(v=>v.startsWith('<!doctype html>')));}
 finally{globalThis.fetch=oldFetch;}
});
test('publicarea stale este refuzată înainte de a crea un commit',async()=>{const oldFetch=globalThis.fetch;let requests=0;globalThis.fetch=async(url)=>{requests++;return String(url).includes('/contents/')?Response.json({content:Buffer.from(JSON.stringify(initial)).toString('base64')}):Response.json({object:{sha:'b'.repeat(40)}})};try{await assert.rejects(()=>editorApi(new Request('https://site.test/api/editor/publish',{method:'POST',headers:{Origin:'https://site.test','Content-Type':'application/json'},body:JSON.stringify({content:initial,revision:'a'.repeat(40),requestId:'00000000-0000-4000-8000-000000000000',images:[]})}),{GITHUB_REPOSITORY:'client/clean',GITHUB_TOKEN:'test-only',EDITOR_DB:{prepare:()=>({bind(){return this},async first(){return null}})}},{requireAdmin:async()=>{},ApiError,json,readLimited}),{status:409});assert.equal(requests,2);}finally{globalThis.fetch=oldFetch;}});

test('reîncercarea după un commit deja salvat nu creează un commit duplicat',async()=>{const oldFetch=globalThis.fetch,requestId='00000000-0000-4000-8000-000000000001',latest=structuredClone(initial);latest.publicationId=requestId;let requests=0;globalThis.fetch=async(url)=>{requests++;return String(url).includes('/contents/')?Response.json({content:Buffer.from(JSON.stringify(latest)).toString('base64')}):Response.json({object:{sha:'b'.repeat(40)}})};try{const response=await editorApi(new Request('https://site.test/api/editor/publish',{method:'POST',headers:{Origin:'https://site.test','Content-Type':'application/json'},body:JSON.stringify({content:initial,revision:'a'.repeat(40),requestId,images:[]})}),{GITHUB_REPOSITORY:'client/clean',GITHUB_TOKEN:'test-only',EDITOR_DB:{prepare:()=>({bind(){return this},async first(){return null}})}},{requireAdmin:async()=>{},ApiError,json,readLimited});assert.equal(response.status,200);assert.equal((await response.json()).revision,'b'.repeat(40));assert.equal(requests,2);}finally{globalThis.fetch=oldFetch;}});


test('galeria respinge surse executabile, traversarea și tipurile greșite de media',()=>{for(const change of [c=>c.gallery.items[0].src='assets/gallery/../../admin.js',c=>c.gallery.items[0].source='javascript:alert(1)',c=>c.gallery.items[0].src='assets/gallery/abt-mocheta.mp4',c=>c.gallery.items[1].id=c.gallery.items[0].id]){const c=structuredClone(initial);change(c);assert.throws(()=>validateContent(c));}const c=structuredClone(initial);c.gallery.items[0].title='<script>alert(1)</script>';const html=renderHomepage(c);assert.ok(html.includes('&lt;script&gt;alert(1)&lt;/script&gt;'));assert.ok(!html.includes('<script>alert(1)</script>'));});

test('un clip cu hash incorect sau copertă lipsă este respins înainte de commit',async()=>{
 const oldFetch=globalThis.fetch,content=structuredClone(initial),video=content.gallery.items.find(v=>v.type==='video'),bytes=await fs.readFile(new URL('../'+video.src,import.meta.url));video.src='assets/uploads/'+createHash('sha256').update(bytes).digest('hex')+'.mp4';let requests=0;globalThis.fetch=async(url)=>{requests++;return String(url).includes('/contents/')?Response.json({content:Buffer.from(JSON.stringify(initial)).toString('base64')}):Response.json({object:{sha:'a'.repeat(40)}})};
 const env={GITHUB_REPOSITORY:'client/clean',GITHUB_TOKEN:'test-only',EDITOR_DB:{prepare:()=>({bind(){return this},async first(){return null}})}},helpers={requireAdmin:async()=>{},ApiError,json,readLimited};
 try{for(const mode of ['hash','poster']){const c=structuredClone(content),v=c.gallery.items.find(x=>x.type==='video'),upload={path:video.src,base64:bytes.toString('base64')};if(mode==='hash'){const broken=Buffer.from(bytes);broken[20]^=1;upload.base64=broken.toString('base64');}else v.poster='assets/uploads/'+'f'.repeat(64)+'.webp';requests=0;await assert.rejects(()=>editorApi(new Request('https://site.test/api/editor/publish',{method:'POST',headers:{Origin:'https://site.test','Content-Type':'application/json'},body:JSON.stringify({content:c,revision:'a'.repeat(40),requestId:'00000000-0000-4000-8000-000000000002',images:[upload]})}),env,helpers),{status:400});assert.equal(requests,2);}}
 finally{globalThis.fetch=oldFetch;}
});
